export const icons = {
  archive: new URL('./assets/icons/archive.svg', import.meta.url).href,
  'arrow-down': new URL('./assets/icons/arrow-down.svg', import.meta.url).href,
  'arrow-left': new URL('./assets/icons/arrow-left.svg', import.meta.url).href,
  'arrow-right': new URL('./assets/icons/arrow-right.svg', import.meta.url).href,
  'arrow-up': new URL('./assets/icons/arrow-up.svg', import.meta.url).href,
  banknote: new URL('./assets/icons/banknote.svg', import.meta.url).href,
  'bar-chart-3': new URL('./assets/icons/bar-chart-3.svg', import.meta.url).href,
  book: new URL('./assets/icons/book.svg', import.meta.url).href,
  bot: new URL('./assets/icons/bot.svg', import.meta.url).href,
  briefcase: new URL('./assets/icons/briefcase.svg', import.meta.url).href,
  calculator: new URL('./assets/icons/calculator.svg', import.meta.url).href,
  calendar: new URL('./assets/icons/calendar.svg', import.meta.url).href,
  camera: new URL('./assets/icons/camera.svg', import.meta.url).href,
  'check-circle': new URL('./assets/icons/check-circle.svg', import.meta.url).href,
  cloud: new URL('./assets/icons/cloud.svg', import.meta.url).href,
  code: new URL('./assets/icons/code.svg', import.meta.url).href,
  coffee: new URL('./assets/icons/coffee.svg', import.meta.url).href,
  'corner-down-left': new URL('./assets/icons/corner-down-left.svg', import.meta.url).href,
  'corner-down-right': new URL('./assets/icons/corner-down-right.svg', import.meta.url).href,
  cpu: new URL('./assets/icons/cpu.svg', import.meta.url).href,
  'credit-card': new URL('./assets/icons/credit-card.svg', import.meta.url).href,
  eye: new URL('./assets/icons/eye.svg', import.meta.url).href,
  'eye-off': new URL('./assets/icons/eye-off.svg', import.meta.url).href,
  file: new URL('./assets/icons/file.svg', import.meta.url).href,
  'file-check': new URL('./assets/icons/file-check.svg', import.meta.url).href,
  'file-plus': new URL('./assets/icons/file-plus.svg', import.meta.url).href,
  'file-search': new URL('./assets/icons/file-search.svg', import.meta.url).href,
  'file-text': new URL('./assets/icons/file-text.svg', import.meta.url).href,
  filter: new URL('./assets/icons/filter.svg', import.meta.url).href,
  film: new URL('./assets/icons/film.svg', import.meta.url).href,
  folder: new URL('./assets/icons/folder.svg', import.meta.url).href,
  'folder-open': new URL('./assets/icons/folder-open.svg', import.meta.url).href,
  'folder-plus': new URL('./assets/icons/folder-plus.svg', import.meta.url).href,
  gift: new URL('./assets/icons/gift.svg', import.meta.url).href,
  globe: new URL('./assets/icons/globe.svg', import.meta.url).href,
  github: new URL('./assets/icons/github.svg', import.meta.url).href,
  groq: new URL('./assets/icons/groq.svg', import.meta.url).href,
  'hard-drive': new URL('./assets/icons/hard-drive.svg', import.meta.url).href,
  headphones: new URL('./assets/icons/headphones.svg', import.meta.url).href,
  heart: new URL('./assets/icons/heart.svg', import.meta.url).href,
  image: new URL('./assets/icons/image.svg', import.meta.url).href,
  info: new URL('./assets/icons/info.svg', import.meta.url).href,
  keyboard: new URL('./assets/icons/keyboard.svg', import.meta.url).href,
  key: new URL('./assets/icons/key.svg', import.meta.url).href,
  laptop: new URL('./assets/icons/laptop.svg', import.meta.url).href,
  link: new URL('./assets/icons/link.svg', import.meta.url).href,
  lock: new URL('./assets/icons/lock.svg', import.meta.url).href,
  'map-pin': new URL('./assets/icons/map-pin.svg', import.meta.url).href,
  mic: new URL('./assets/icons/mic.svg', import.meta.url).href,
  monitor: new URL('./assets/icons/monitor.svg', import.meta.url).href,
  mistral: new URL('./assets/icons/mistral.svg', import.meta.url).href,
  mouse: new URL('./assets/icons/mouse.svg', import.meta.url).href,
  music: new URL('./assets/icons/music.svg', import.meta.url).href,
  openai: new URL('./assets/icons/openai.svg', import.meta.url).href,
  ollama: new URL('./assets/icons/ollama.svg', import.meta.url).href,
  openrouter: new URL('./assets/icons/OpenRouter.svg', import.meta.url).href,
  package: new URL('./assets/icons/package.svg', import.meta.url).href,
  perplexity: new URL('./assets/icons/perplexity.svg', import.meta.url).href,
  palette: new URL('./assets/icons/palette.svg', import.meta.url).href,
  paperclip: new URL('./assets/icons/paperclip.svg', import.meta.url).href,
  'pen-tool': new URL('./assets/icons/pen-tool.svg', import.meta.url).href,
  'pie-chart': new URL('./assets/icons/pie-chart.svg', import.meta.url).href,
  plug: new URL('./assets/icons/plug.svg', import.meta.url).href,
  power: new URL('./assets/icons/power.svg', import.meta.url).href,
  printer: new URL('./assets/icons/printer.svg', import.meta.url).href,
  puzzle: new URL('./assets/icons/puzzle.svg', import.meta.url).href,
  google: new URL('./assets/icons/google.svg', import.meta.url).href,
  'refresh-cw': new URL('./assets/icons/refresh-cw.svg', import.meta.url).href,
  repeat: new URL('./assets/icons/repeat.svg', import.meta.url).href,
  search: new URL('./assets/icons/search.svg', import.meta.url).href,
  shield: new URL('./assets/icons/shield.svg', import.meta.url).href,
  shuffle: new URL('./assets/icons/shuffle.svg', import.meta.url).href,
  smartphone: new URL('./assets/icons/smartphone.svg', import.meta.url).href,
  speaker: new URL('./assets/icons/speaker.svg', import.meta.url).href,
  star: new URL('./assets/icons/star.svg', import.meta.url).href,
  tag: new URL('./assets/icons/tag.svg', import.meta.url).href,
  together: new URL('./assets/icons/togetherai.svg', import.meta.url).href,
  upload: new URL('./assets/icons/upload.svg', import.meta.url).href,
  user: new URL('./assets/icons/user.svg', import.meta.url).href,
  video: new URL('./assets/icons/video.svg', import.meta.url).href,
  'volume-2': new URL('./assets/icons/volume-2.svg', import.meta.url).href,
  wind: new URL('./assets/icons/wind.svg', import.meta.url).href,
  azure: new URL('./assets/icons/azure.svg', import.meta.url).href,
  x: new URL('./assets/icons/Grok.svg', import.meta.url).href,
  zap: new URL('./assets/icons/zap.svg', import.meta.url).href,
  deepseek: new URL('./assets/icons/deepseek.svg', import.meta.url).href,
  anthropic: new URL('./assets/icons/Anthropic.svg', import.meta.url).href
}

const iconAliases = {
  '\u{1F5BC}\u{FE0F}': 'image',
  '\u{1F4F9}': 'video',
  '\u{1F4C4}': 'file-text',
  '\u{1F3B5}': 'music',
  '\u{1F4E6}': 'archive',
  '</>': 'code',
  '\u{1F4C1}': 'folder',
  '\u{1F3A8}': 'pen-tool',
  '\u{1F4DA}': 'book',
  '\u{1F170}\u{FE0F}': 'zap',
  '\u{2601}\u{FE0F}': 'cloud',
  '\u{1F50D}': 'search',
  '\u{1F419}': 'github',
  '\u{1F310}': 'globe',
  '\u{39}\u{FE0F}\u{20E3}': 'zap',
  '\u{1F30A}': 'wind',
  '\u{1F999}': 'cpu',
  '\u{1F916}': 'bot',
  '\u{1F500}': 'shuffle',
  '\u{1F9E9}': 'puzzle',
  '\u{1F517}': 'link',
  '\u{274C}': 'x'
}

export function resolveIconKey(key) {
  if (!key) return 'folder'
  if (icons[key]) return key
  if (iconAliases[key]) return iconAliases[key]
  return 'folder'
}

export function getIcon(key) {
  return icons[resolveIconKey(key)]
}
